### ISSUE TITLE
I want translate this patch , it is be posibility.?

### ISSUE THREAD

**Issue by ghost** [Ingvix/sailfishos-patch-improved-notification-preview#1]

**Comment by Ingvix** [comment]
You can, indeed. Maybe I should add a readme file here too. There was already a transifex link in Openrepo's description. [Here it is](https://www.transifex.com/ingvix/improved-notification-preview/).
It's my first time using Transifex so I'm not sure if it's currently allowing you to create a translation there but if you face any trouble, do tell and I will look into it.

**Comment by ghost** [comment]
I do not use transifex, can i use PR?

**Comment by Ingvix** [comment]
I don't know what that is but I [committed the english .ts file](https://github.com/Ingvix/sailfishos-patch-improved-notification-preview/blob/master/sailfishos-patch-improved-notification-preview_eng_en.ts) so you can use it to translate how ever you wish. Then deliver it to me and I'll add it to the patch.

**Comment by ghost** [comment]
Hello Ingvix
[sailfishos-patch-improved-notification-preview-es.zip](https://github.com/Ingvix/sailfishos-patch-improved-notification-preview/files/1438526/sailfishos-patch-improved-notification-preview-es.zip)

**Comment by Ingvix** [comment]
It seems you've sort of misunderstood the point of id based translation. You were not suppose to translate the source string as it is only for id for the string and not the actual visible string in the UI. You were suppose to replace the english translation string with translation to your own language.

**Comment by ghost** [comment]
I already assumed that. I will fix now, thx.

**Comment by ghost** [comment]
[sailfishos-patch-improved-notification-preview-es.zip](https://github.com/Ingvix/sailfishos-patch-improved-notification-preview/files/1438953/sailfishos-patch-improved-notification-preview-es.zip)

**Comment by Ingvix** [comment]
Thanks! The new release is now available on [Openrepos](https://openrepos.net/content/ingvix/patch-improved-notification-preview).

**Comment by ghost** [comment]
Thx.

**Comment by ghost** [comment]
Hello Ingvix
**External Feature Request:** I Know your are expert on sailfish system. I want to revive an app, a very important to me but I do not have much knowledge about the internal system of sailfish, you are it. https://github.com/Caballlero/jolla-settings-tor-button The original developer of this app is coderus, but it seems that he is not interested anymore of this. So I wanted to ask you if you can **Fork it** and **Fix it** some problems that it have especially with the icon path, do not show icon after installing it in the system, something else would also be to pass them from security to connectivity section. My total problem is that I can not put the icon of the system in its correct route so  it not  visualized in the internal system of icons. 
**Thanks in Advance.**

**Comment by Ingvix** [comment]
I wouldn't call myself an expert. More like an experienced beginner. 

I looked around a bit and the problems seem quite simple to fix. I can't promise anything but I'll try to tinker it a bit when I have the time.

**Comment by ghost** [comment]
Thanks Ingvix
I tried to clone your icon path over your Amazing App, but it seems that that information is not shared in the github yet.

**Comment by Ingvix** [comment]
I'm using icon that already exist in the system for this patch's settings entry so it's a bit different deal than providing your own icon.

**Comment by ghost** [comment]
ah ok thanks
